# Generated by Django 6.0.2 on 2026-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('Email', models.EmailField(max_length=255)),
                ('Entreprise', models.CharField(max_length=255, unique=True)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastcreated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
