# Generated by Django 6.0.2 on 2026-02-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='type_demande',
            field=models.CharField(choices=[('', 'Sélectionner une option'), ('mobile', 'Développement Mobile'), ('web', 'Développement Web'), ('logiciel', 'Logiciel'), ('Denade', 'Autre Demande')], default='', max_length=50),
        ),
    ]
